---
name: ShellCheck

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - bin/*
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck bin/*
        run: shellcheck bin/*
